<a href="https://colab.research.google.com/github/s23067657-cell/midterm-1-AI-course/blob/main/midterm1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Midterm 1: run the data generator in Colab

Use this notebook if you cannot run Python or git on your own machine. It only **generates and shows your data**. You write your answers in `ANSWERS.md` on **your fork on github.com** (open the file, click the pencil icon, edit, *Commit changes*), then submit the commit URL in Canvas. See the README for the rules.

1. Fill in `GITHUB_USERNAME` (the account that owns your fork) and `CODE` (`PRACTICE` to rehearse; the real code is on the board during the exam).
2. Run the three code cells in order.

In [ ]:
GITHUB_USERNAME = "s23067657-cell"   # e.g. "aigerim-k"
CODE = "KETTLE-62"      # replace with the session code during the exam
assert GITHUB_USERNAME, "fill in GITHUB_USERNAME first"

In [ ]:
import os

if not os.path.exists("midterm-1-AI-course"):
    !git clone --quiet https://github.com/unreal-kz/midterm-1-AI-course.git
%cd midterm-1-AI-course
!python make_my_data.py --github s23067657-cell --code kettle-62

/content/midterm-1-AI-course/midterm-1-AI-course/midterm-1-AI-course/midterm-1-AI-course/midterm-1-AI-course/midterm-1-AI-course/midterm-1-AI-course
Wrote 3 files to my_data/ · fingerprint 83527391
Next: open my_data/DATA.md

In [ ]:
import pandas as pd
from IPython.display import Markdown, display

display(Markdown(open("my_data/DATA.md", encoding="utf-8").read()))
ranks = pd.read_csv("my_data/retrieval_ranks.csv")   # Part 1
docs = pd.read_csv("my_data/doc_results.csv")        # Part 2
display(ranks.head(), docs)

# Midterm 1: your data

GitHub username: `s23067657-cell` · session code: `kettle-62` · generator v1

**Fingerprint: `83527391`**: copy it into the first lines of `ANSWERS.md`. All numbers below are synthetic: this is an exam, not a measurement.

## Part 1: inputs

`retrieval_ranks.csv`: 60 test questions (20 EN, 20 RU, 20 KK). `rank_A` and `rank_B` give the position of the correct chunk in the top 10 retrieved under config A and config B; **11 means the correct chunk was not in the top 10.**

Production traffic and Model M token counts (tokens per item, as counted by Model M's tokenizer):

| language | share of traffic | question tokens | answer tokens | chunk A tokens | chunk B tokens |
|---|---|---|---|---|---|
| EN | 34 % | 31 | 139 | 269 | 80 |
| RU | 40 % | 44 | 196 | 379 | 113 |
| KK | 26 % | 105 | 470 | 909 | 270 |

- Requests per day: **7,000**, in the traffic shares above.
- System prompt: **197** tokens in every request.
- Price: **$3** per million input tokens, **$15** per million output tokens.
- Annual budget for this service (model calls only): **$19,700**.

## Part 2: inputs

`doc_results.csv`: for each pipeline, language and scan condition, `n_docs` test invoices and `n_correct` = invoices whose number, date, seller ID and total were all extracted exactly (strict scorer, as in Lab 04).

- **Pipeline H**: hosted vision-language API in a data centre abroad, pay per token; each page is sent as an image.
- **Pipeline L**: open vision-language model on your own server in Kazakhstan, fixed monthly cost.

- Volume: **9,000** scanned pages per day. In **8 %** of them an individual's name and ИИН are printed (sole proprietors, receipts).
- Page image: **1654 × 2339** pixels. Pipeline H counts an image as ⌈width ÷ 28⌉ × ⌈height ÷ 28⌉ input tokens and returns about **344** output tokens per page (the JSON).
- Pipeline H price: **$2** per million input tokens, **$10** per million output tokens.
- Pipeline L: one server costs **$750** per month and handles up to **6,000** pages per day; add servers as needed.

## Part 3: your five questions

Answer each in `ANSWERS.md`: one **Number** line and one **Why** line of at most 40 words.

### Q1

One complaint sentence, measured three ways (synthetic numbers):

| | characters | UTF-8 bytes | tokens (Model M) |
|---|---|---|---|
| EN | 298 | 298 | 54 |
| RU | 333 | 633 | 76 |
| KK | 337 | 638 | 183 |

Compute the KK÷EN ratio for characters, for bytes and for tokens. **Number:** the token ratio divided by the byte ratio (2 decimals). **Why** (at most 40 words): what does this number say about where the Kazakh premium comes from, the encoding or the tokenizer?

### Q2

A teammate sets the chunk size to **640 tokens, counted with cl100k**. The retrieval model (e5-small) reads at most 512 of *its own* tokens. Assume e5 tokens grow in proportion to cl100k tokens at the rate measured in Lecture 4.1 (a chunker told 256 cl100k tokens produced chunks of 263 / 128 / 76 e5 tokens for EN / RU / KK), and that every chunk is exactly the full size.

In an English chunk, the sentence that contains the answer starts 85 % of the way into the chunk and is shorter than 20 e5 tokens. **Number:** the position of the start of that sentence, in e5 tokens (nearest integer). **Why** (at most 40 words): can a question that matches only that sentence retrieve this chunk, and would you see an error?

### Q3

A language model gives these next-token scores for the prompt "The branch is closed on":

| token | score |
|---|---|
| Monday | 3.6 |
| Friday | 3.0 |
| Sunday | 1.7 |
| holiday | 0.4 |
| Easter | -0.8 |

Use temperature T = 1, then apply top-p = 0.8. **Number:** the probability of the top token after top-p and renormalisation, in percent (1 decimal). **Why** (at most 40 words): how does top-p differ from lowering the temperature?

### Q4

Two models answer the same 100 factual questions (1 point per correct answer on the public leaderboard):

| | correct | wrong | "I don't know" |
|---|---|---|---|
| Model X | 72 | 28 | 0 |
| Model Y | 66 | 11 | 23 |

Now score them again with a penalty: +1 per correct answer, −2 per wrong answer, 0 for "I don't know". **Number:** Y's penalised score minus X's (negative if X is ahead). **Why** (at most 40 words): which model does the public leaderboard prefer, and what does that teach a model to do?

### Q5

A lab trains a model with **34 billion parameters on 7.956 trillion tokens**. Chinchilla (Lecture 1.1) trained 70 billion parameters on 1.4 trillion tokens, which the paper presents as the compute-optimal ratio. **Number:** this model's tokens per parameter divided by Chinchilla's tokens per parameter (2 decimals). **Why** (at most 40 words): is the model under- or over-trained by that criterion, and what did Chinchilla say about models such as GPT-3?

   qid lang  rank_A  rank_B
0  q01   RU       1       3
1  q02   KK       1       1
2  q03   RU       1       1
3  q04   EN       1       1
4  q05   EN       1       1

   pipeline lang condition  n_docs  n_correct
0         H   EN     clean      30         29
1         H   EN  degraded      30         27
2         H   RU     clean      30         28
3         H   RU  degraded      30         25
4         H   KK     clean      30         29
5         H   KK  degraded      30         21
6         L   EN     clean      30         27
7         L   EN  degraded      30         24
8         L   RU     clean      30         27
9         L   RU  degraded      30         23
10        L   KK     clean      30         25
11        L   KK  degraded      30         21

`ranks` and `docs` are ready for you to compute with. Remember the **fingerprint** at the top of the data sheet: it goes into the first lines of `ANSWERS.md`.

In [ ]:
import math, pandas as pd

ranks = pd.read_csv("my_data/retrieval_ranks.csv")
print(ranks.columns.tolist())
lang_col = [c for c in ranks.columns
            if ranks[c].astype(str).isin(["EN","RU","KK"]).any()][0]

def wilson(h, n, z=1.96):
    p = h/n; d = 1 + z*z/n
    c = (p + z*z/(2*n))/d
    w = z*math.sqrt(p*(1-p)/n + z*z/(4*n*n))/d
    return round(c-w,3), round(c+w,3)

def mrr(s): return sum(1/r for r in s if r <= 10)/len(s)

print("\n=== 1a ===")
for cfg in "AB":
    s = ranks[f"rank_{cfg}"]
    print(cfg, "recall@1/3/5:", [round((s<=k).mean(),4) for k in (1,3,5)],
          "MRR@10:", round(mrr(s),4))

print("\n=== 1b ===")
for cfg in "AB":
    for k in (3,5):
        s = ranks[f"rank_{cfg}"]; h = int((s<=k).sum())
        print(f"({cfg},{k}) hits={h}/60 recall={h/60:.4f} Wilson={wilson(h,60)}")

share = {"EN":.34,"RU":.40,"KK":.26}
q  = {"EN":31,"RU":44,"KK":105}
a  = {"EN":139,"RU":196,"KK":470}
ch = {"A":{"EN":269,"RU":379,"KK":909}, "B":{"EN":80,"RU":113,"KK":270}}
SYS, PIN, POUT, REQ, BUDGET = 197, 3, 15, 7000, 19700

def annual(cfg, k):
    tot = 0
    for l in share:
        inp = SYS + q[l] + k*ch[cfg][l]
        tot += share[l]*(inp*PIN + a[l]*POUT)/1e6
    return tot*REQ*365

print("\n=== 1c (budget $19,700) ===")
for cfg in "AB":
    for k in (3,5):
        c = annual(cfg,k)
        print(f"({cfg},{k}) ${c:,.0f}", "OK" if c <= BUDGET else "OVER BUDGET")

print("\n=== per-language recall (n=20) ===")
for cfg in "AB":
    for k in (3,5):
        for l in ["EN","RU","KK"]:
            s = ranks[ranks[lang_col]==l][f"rank_{cfg}"]; h = int((s<=k).sum())
            print(f"({cfg},{k}) {l}: {h}/20 = {h/20:.2f}, Wilson={wilson(h,20)}")

['qid', 'lang', 'rank_A', 'rank_B']

=== 1a ===
A recall@1/3/5: [np.float64(0.5667), np.float64(0.7), np.float64(0.8)] MRR@10: 0.6485
B recall@1/3/5: [np.float64(0.3333), np.float64(0.5833), np.float64(0.6333)] MRR@10: 0.4523

=== 1b ===
(A,3) hits=42/60 recall=0.7000 Wilson=(0.575, 0.801)
(A,5) hits=48/60 recall=0.8000 Wilson=(0.682, 0.882)
(B,3) hits=35/60 recall=0.5833 Wilson=(0.457, 0.699)
(B,5) hits=38/60 recall=0.6333 Wilson=(0.507, 0.744)

=== 1c (budget $19,700) ===
(A,3) $22,458 OVER BUDGET
(A,5) $29,807 OVER BUDGET
(B,3) $14,713 OK
(B,5) $16,899 OK

=== per-language recall (n=20) ===
(A,3) EN: 15/20 = 0.75, Wilson=(0.531, 0.888)
(A,3) RU: 17/20 = 0.85, Wilson=(0.64, 0.948)
(A,3) KK: 10/20 = 0.50, Wilson=(0.299, 0.701)
(A,5) EN: 16/20 = 0.80, Wilson=(0.584, 0.919)
(A,5) RU: 18/20 = 0.90, Wilson=(0.699, 0.972)
(A,5) KK: 14/20 = 0.70, Wilson=(0.481, 0.855)
(B,3) EN: 11/20 = 0.55, Wilson=(0.342, 0.742)
(B,3) RU: 14/20 = 0.70, Wilson=(0.481, 0.855)
(B,3) KK: 10/20 = 0.50, Wilson=(0.299, 0.701)
(B,5) EN: 11/20 = 0.55, Wilson=(0.342, 0.742)
(B,5) RU: 17/20 = 0.85, Wilson=(0.64, 0.948)
(B,5) KK: 10/20 = 0.50, Wilson=(0.299, 0.701)

In [ ]:
txt = open("my_data/DATA.md", encoding="utf-8").read()
print(txt[txt.index("Part 2"):])

import pandas as pd
docs = pd.read_csv("my_data/doc_results.csv")
print(docs.columns.tolist())
print(len(docs))
print(docs.to_string())

Part 2: inputs

`doc_results.csv`: for each pipeline, language and scan condition, `n_docs` test invoices and `n_correct` = invoices whose number, date, seller ID and total were all extracted exactly (strict scorer, as in Lab 04).

- **Pipeline H**: hosted vision-language API in a data centre abroad, pay per token; each page is sent as an image.
- **Pipeline L**: open vision-language model on your own server in Kazakhstan, fixed monthly cost.

- Volume: **9,000** scanned pages per day. In **8 %** of them an individual's name and ИИН are printed (sole proprietors, receipts).
- Page image: **1654 × 2339** pixels. Pipeline H counts an image as ⌈width ÷ 28⌉ × ⌈height ÷ 28⌉ input tokens and returns about **344** output tokens per page (the JSON).
- Pipeline H price: **$2** per million input tokens, **$10** per million output tokens.
- Pipeline L: one server costs **$750** per month and handles up to **6,000** pages per day; add servers as needed.

## Part 3: your five questions

Answer each in `ANSWERS.md`: one **Number** line and one **Why** line of at most 40 words.

### Q1

One complaint sentence, measured three ways (synthetic numbers):

| | characters | UTF-8 bytes | tokens (Model M) |
|---|---|---|---|
| EN | 298 | 298 | 54 |
| RU | 333 | 633 | 76 |
| KK | 337 | 638 | 183 |

Compute the KK÷EN ratio for characters, for bytes and for tokens. **Number:** the token ratio divided by the byte ratio (2 decimals). **Why** (at most 40 words): what does this number say about where the Kazakh premium comes from, the encoding or the tokenizer?

### Q2

A teammate sets the chunk size to **640 tokens, counted with cl100k**. The retrieval model (e5-small) reads at most 512 of *its own* tokens. Assume e5 tokens grow in proportion to cl100k tokens at the rate measured in Lecture 4.1 (a chunker told 256 cl100k tokens produced chunks of 263 / 128 / 76 e5 tokens for EN / RU / KK), and that every chunk is exactly the full size.

In an English chunk, the sentence that contains the answer starts 85 % of the way into the chunk and is shorter than 20 e5 tokens. **Number:** the position of the start of that sentence, in e5 tokens (nearest integer). **Why** (at most 40 words): can a question that matches only that sentence retrieve this chunk, and would you see an error?

### Q3

A language model gives these next-token scores for the prompt "The branch is closed on":

| token | score |
|---|---|
| Monday | 3.6 |
| Friday | 3.0 |
| Sunday | 1.7 |
| holiday | 0.4 |
| Easter | -0.8 |

Use temperature T = 1, then apply top-p = 0.8. **Number:** the probability of the top token after top-p and renormalisation, in percent (1 decimal). **Why** (at most 40 words): how does top-p differ from lowering the temperature?

### Q4

Two models answer the same 100 factual questions (1 point per correct answer on the public leaderboard):

| | correct | wrong | "I don't know" |
|---|---|---|---|
| Model X | 72 | 28 | 0 |
| Model Y | 66 | 11 | 23 |

Now score them again with a penalty: +1 per correct answer, −2 per wrong answer, 0 for "I don't know". **Number:** Y's penalised score minus X's (negative if X is ahead). **Why** (at most 40 words): which model does the public leaderboard prefer, and what does that teach a model to do?

### Q5

A lab trains a model with **34 billion parameters on 7.956 trillion tokens**. Chinchilla (Lecture 1.1) trained 70 billion parameters on 1.4 trillion tokens, which the paper presents as the compute-optimal ratio. **Number:** this model's tokens per parameter divided by Chinchilla's tokens per parameter (2 decimals). **Why** (at most 40 words): is the model under- or over-trained by that criterion, and what did Chinchilla say about models such as GPT-3?

['pipeline', 'lang', 'condition', 'n_docs', 'n_correct']
12
   pipeline lang condition  n_docs  n_correct
0         H   EN     clean      30         29
1         H   EN  degraded      30         27
2         H   RU     clean      30         28
3         H   RU  degraded      30         25
4         H   KK     clean      30         29
5         H   KK  degraded      30         21
6         L   EN     clean      30         27
7         L   EN  degraded      30         24
8         L   RU     clean      30         27
9         L   RU  degraded      30         23
10        L   KK     clean      30         25
11        L   KK  degraded      30         21